name: Release

on:
  push:
    branches: [main, release-candidate, develop]
    paths-ignore:
      - '.github/**'
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
      - '.golangci.yml'
      - '.golangci.yaml'

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: read

jobs:
  release:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/release.yml@v1.28.5
    with:
      enable_changelog: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
